# Generated by Django 5.2 on 2026-07-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='chef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant_1.chef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='restaurant_1.restaurant'),
            preserve_default=False,
        ),
    ]
